version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install -g serverless
      - npm install
  pre_build:
    commands:
      - echo Build started on `date`
  build:
    commands:
      - serverless deploy --stage prod --region ap-southeast-1
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'