version: 0.2

env:
  variables:
    DB_SECRET_ARN: "arn:aws:secretsmanager:ap-southeast-1:194416698840:secret:rds!db-498e9ad0-b353-492d-84bb-640ddffd016d"

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install -g serverless
      - npm install
  pre_build:
    commands:
      - echo Build started on `date`
  build:
    commands:
      - serverless deploy --stage pipeline --region ap-southeast-1
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'